spring:
  application: 
   name: Eureka

server:
   port: 2222

eureka: 
  client:
    service-url:
          defaultZone: http://3.133.85.181:2222/eureka
    eureka-server-port: 2222
  us-east-2:
       availabilityZone: us-east-2c        